import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Terminal as XTerm } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import './styles.css';
type Agent = { id:string; sessionId:string; workspace:string; branch?:string; title:string }; type Worktree = { id:string; label:string; path:string; available:boolean }; type Dashboard = { agents:Agent[]; worktrees:Worktree[] };
let csrf = ''; const request = async (url:string, init:RequestInit = {}) => { const headers = new Headers(init.headers); if (csrf) headers.set('X-CSRF-Token', csrf); return fetch(url, { ...init, credentials:'same-origin', headers }); };
function Login({ done }:{done:()=>void}) { const [password,setPassword]=useState(''); const [error,setError]=useState(''); useEffect(()=>{ fetch('/api/auth/bootstrap',{credentials:'same-origin'}).then(r=>r.json()).then(x=>csrf=x.csrfToken).catch(()=>setError('Unable to connect')); },[]); const login=async(e:React.FormEvent)=>{e.preventDefault(); const r=await request('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password})}); if(!r.ok)return setError('Invalid credentials'); csrf=(await r.json()).csrfToken; setPassword(''); done();}; return <main className="login"><form onSubmit={login}><h1>Remote Agent Console</h1><label>Password<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error&&<p role="alert">{error}</p>}<button>Sign in</button></form></main> }
function Prompt({ id }:{id:string}) { const [value,setValue]=useState(''); const [pending,setPending]=useState(false); const submit=async()=>{if(!value||pending)return;setPending(true);try{const r=await request(`/api/agents/${encodeURIComponent(id)}/prompt`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt:value})});if(r.ok)setValue('');}finally{setPending(false)}}; return <section><label>Prompt<textarea aria-label="Prompt" value={value} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();void submit();}else if(e.key==='Tab'){e.preventDefault();setValue(v=>v+'\t');}else if(e.key==='Enter'&&!e.ctrlKey&&!e.metaKey){e.preventDefault();setValue(v=>v+'\n');}}} onChange={e=>setValue(e.target.value)} /></label><button disabled={pending||!value} onClick={()=>void submit()}>{pending?'Sending…':'Send prompt'}</button><small>Tab inserts a tab · Enter inserts a newline · Ctrl/Cmd+Enter submits</small></section> }
function Log({ id }:{id:string}) { const [log,setLog]=useState(''); useEffect(()=>{let ws:WebSocket|undefined;let closed=false; request(`/api/agents/${encodeURIComponent(id)}/tickets`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'logs'})}).then(r=>r.json()).then(({ticket})=>{if(closed)return;ws=new WebSocket(`${location.origin.replace(/^http/,'ws')}/ws/logs/${encodeURIComponent(id)}`,['rac',ticket]);ws.onmessage=e=>{const f=JSON.parse(e.data);setLog((v:string)=>f.type==='append'?v+f.text:f.text)}}).catch(()=>{});return()=>{closed=true;ws?.close()};},[id]);return <pre className="log" aria-label="Live log">{log||'Waiting for output…'}</pre> }
function AgentCard({agent}:{agent:Agent}) { const [terminal,setTerminal]=useState(false); return <article className="card"><h2>{agent.title||agent.workspace}</h2><p>{agent.workspace}{agent.branch&&` · ${agent.branch}`}</p><Log id={agent.id}/><Prompt id={agent.id}/><button onClick={()=>setTerminal(true)}>Open terminal</button>{terminal&&<div className="dialog" role="dialog"><div><h2>Session-scoped terminal</h2><p>This terminal can view and control every pane in its owning tmux session; its current pane may differ from this card.</p><p>Session: {agent.sessionId}</p><button onClick={()=>setTerminal(false)}>Close</button><Terminal agent={agent}/></div></div>}</article> }
function Terminal({agent}:{agent:Agent}){const host=useRef<HTMLDivElement | null>(null);const socket=useRef<WebSocket | undefined>(undefined);const [connected,setConnected]=useState(false);useEffect(()=>()=>socket.current?.close(),[]);const connect=async()=>{const r=await request(`/api/agents/${encodeURIComponent(agent.id)}/tickets`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'terminal'})});const {ticket}=await r.json();const term=new XTerm({cursorBlink:true,theme:{background:'#020617'}});const fit=new FitAddon();term.loadAddon(fit);term.open(host.current!);fit.fit();const ws=new WebSocket(`${location.origin.replace(/^http/,'ws')}/ws/terminal/${encodeURIComponent(agent.id)}`,['rac',ticket]);socket.current=ws;const bytes=(text:string)=>Uint8Array.from(atob(text.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const b64=(text:string)=>btoa(String.fromCharCode(...new TextEncoder().encode(text))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');ws.onopen=()=>{setConnected(true);ws.send(JSON.stringify({v:1,type:'resize',cols:term.cols,rows:term.rows}));};ws.onmessage=e=>{const f=JSON.parse(e.data);if(f.type==='output')term.write(bytes(f.data));};term.onData(data=>ws.readyState===WebSocket.OPEN&&ws.send(JSON.stringify({v:1,type:'input',data:b64(data)})));const observer=new ResizeObserver(()=>{fit.fit();if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({v:1,type:'resize',cols:term.cols,rows:term.rows}));});observer.observe(host.current!);ws.onclose=()=>{observer.disconnect();term.dispose();setConnected(false)};};return <section><button disabled={connected} onClick={()=>void connect()}>Confirm and connect</button><div className="terminal" ref={host} aria-label="Interactive session terminal"/></section>}
function DashboardView(){const [data,setData]=useState<Dashboard>();const carousel=useRef<HTMLElement>(null);const refresh=()=>request('/api/dashboard').then(r=>r.ok?r.json():Promise.reject()).then(setData);useEffect(()=>{void refresh()},[]);if(!data)return <main>Loading sessions…</main>;return <main><header><h1>Remote Agent Console</h1><button onClick={()=>void refresh()}>Refresh</button></header><p className="hint">Swipe horizontally or use arrow keys to navigate.</p><section ref={carousel} className="carousel" tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowRight')carousel.current?.scrollBy({left:carousel.current.clientWidth,behavior:'smooth'});if(e.key==='ArrowLeft')carousel.current?.scrollBy({left:-carousel.current.clientWidth,behavior:'smooth'})}}>{data.agents.map(a=><AgentCard key={a.id} agent={a}/>)}{data.worktrees.map(w=><article className="card idle" key={w.id}><h2>{w.label}</h2><p>{w.path}</p><button disabled={!w.available} onClick={()=>void request(`/api/worktrees/${encodeURIComponent(w.id)}/launch`,{method:'POST'})}>Launch configured agent</button></article>)}{!data.agents.length&&!data.worktrees.length&&<article className="card"><h2>No managed sessions</h2><p>Start Codex inside tmux or configure a worktree.</p></article>}</section></main>}
function App(){const [ready,setReady]=useState(false);return ready?<DashboardView/>:<Login done={()=>setReady(true)}/>}; createRoot(document.getElementById('root')!).render(<App/>);
